name: Debug Drift
on:
  workflow_dispatch:
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - name: pub get drift
        run: |
          flutter pub get
          cd example && flutter pub get && cd ..
          echo "----- git diff after pub get -----"
          git --no-pager diff
      - name: format drift
        run: |
          git checkout -- .
          dart format .
          echo "----- git diff after dart format -----"
          git --no-pager diff
